//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMDSS.VahanINFO {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server.web.vahan.nic/", ConfigurationName="VahanINFO.VahanInfo")]
    public interface VahanInfo {
        
        // CODEGEN: Generating message contract since element name client_id from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://server.web.vahan.nic/VahanInfo/getDetailsRequest", ReplyAction="http://server.web.vahan.nic/VahanInfo/getDetailsResponse")]
        FMDSS.VahanINFO.getDetailsResponse getDetails(FMDSS.VahanINFO.getDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server.web.vahan.nic/VahanInfo/getDetailsRequest", ReplyAction="http://server.web.vahan.nic/VahanInfo/getDetailsResponse")]
        System.Threading.Tasks.Task<FMDSS.VahanINFO.getDetailsResponse> getDetailsAsync(FMDSS.VahanINFO.getDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name client_id from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://server.web.vahan.nic/VahanInfo/getChasisDetailsRequest", ReplyAction="http://server.web.vahan.nic/VahanInfo/getChasisDetailsResponse")]
        FMDSS.VahanINFO.getChasisDetailsResponse getChasisDetails(FMDSS.VahanINFO.getChasisDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server.web.vahan.nic/VahanInfo/getChasisDetailsRequest", ReplyAction="http://server.web.vahan.nic/VahanInfo/getChasisDetailsResponse")]
        System.Threading.Tasks.Task<FMDSS.VahanINFO.getChasisDetailsResponse> getChasisDetailsAsync(FMDSS.VahanINFO.getChasisDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name client_id from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://server.web.vahan.nic/VahanInfo/getEngineDetailsRequest", ReplyAction="http://server.web.vahan.nic/VahanInfo/getEngineDetailsResponse")]
        FMDSS.VahanINFO.getEngineDetailsResponse getEngineDetails(FMDSS.VahanINFO.getEngineDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server.web.vahan.nic/VahanInfo/getEngineDetailsRequest", ReplyAction="http://server.web.vahan.nic/VahanInfo/getEngineDetailsResponse")]
        System.Threading.Tasks.Task<FMDSS.VahanINFO.getEngineDetailsResponse> getEngineDetailsAsync(FMDSS.VahanINFO.getEngineDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name return from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://server.web.vahan.nic/VahanInfo/parseCurrentDateToStringRequest", ReplyAction="http://server.web.vahan.nic/VahanInfo/parseCurrentDateToStringResponse")]
        FMDSS.VahanINFO.parseCurrentDateToStringResponse parseCurrentDateToString(FMDSS.VahanINFO.parseCurrentDateToStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server.web.vahan.nic/VahanInfo/parseCurrentDateToStringRequest", ReplyAction="http://server.web.vahan.nic/VahanInfo/parseCurrentDateToStringResponse")]
        System.Threading.Tasks.Task<FMDSS.VahanINFO.parseCurrentDateToStringResponse> parseCurrentDateToStringAsync(FMDSS.VahanINFO.parseCurrentDateToStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDetails", Namespace="http://server.web.vahan.nic/", Order=0)]
        public FMDSS.VahanINFO.getDetailsRequestBody Body;
        
        public getDetailsRequest() {
        }
        
        public getDetailsRequest(FMDSS.VahanINFO.getDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string client_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string regn_no;
        
        public getDetailsRequestBody() {
        }
        
        public getDetailsRequestBody(string client_id, string regn_no) {
            this.client_id = client_id;
            this.regn_no = regn_no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDetailsResponse", Namespace="http://server.web.vahan.nic/", Order=0)]
        public FMDSS.VahanINFO.getDetailsResponseBody Body;
        
        public getDetailsResponse() {
        }
        
        public getDetailsResponse(FMDSS.VahanINFO.getDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getDetailsResponseBody() {
        }
        
        public getDetailsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getChasisDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getChasisDetails", Namespace="http://server.web.vahan.nic/", Order=0)]
        public FMDSS.VahanINFO.getChasisDetailsRequestBody Body;
        
        public getChasisDetailsRequest() {
        }
        
        public getChasisDetailsRequest(FMDSS.VahanINFO.getChasisDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getChasisDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string client_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string chasi_no;
        
        public getChasisDetailsRequestBody() {
        }
        
        public getChasisDetailsRequestBody(string client_id, string chasi_no) {
            this.client_id = client_id;
            this.chasi_no = chasi_no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getChasisDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getChasisDetailsResponse", Namespace="http://server.web.vahan.nic/", Order=0)]
        public FMDSS.VahanINFO.getChasisDetailsResponseBody Body;
        
        public getChasisDetailsResponse() {
        }
        
        public getChasisDetailsResponse(FMDSS.VahanINFO.getChasisDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getChasisDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getChasisDetailsResponseBody() {
        }
        
        public getChasisDetailsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEngineDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEngineDetails", Namespace="http://server.web.vahan.nic/", Order=0)]
        public FMDSS.VahanINFO.getEngineDetailsRequestBody Body;
        
        public getEngineDetailsRequest() {
        }
        
        public getEngineDetailsRequest(FMDSS.VahanINFO.getEngineDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getEngineDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string client_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string engine_no;
        
        public getEngineDetailsRequestBody() {
        }
        
        public getEngineDetailsRequestBody(string client_id, string engine_no) {
            this.client_id = client_id;
            this.engine_no = engine_no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEngineDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEngineDetailsResponse", Namespace="http://server.web.vahan.nic/", Order=0)]
        public FMDSS.VahanINFO.getEngineDetailsResponseBody Body;
        
        public getEngineDetailsResponse() {
        }
        
        public getEngineDetailsResponse(FMDSS.VahanINFO.getEngineDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getEngineDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getEngineDetailsResponseBody() {
        }
        
        public getEngineDetailsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class parseCurrentDateToStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="parseCurrentDateToString", Namespace="http://server.web.vahan.nic/", Order=0)]
        public FMDSS.VahanINFO.parseCurrentDateToStringRequestBody Body;
        
        public parseCurrentDateToStringRequest() {
        }
        
        public parseCurrentDateToStringRequest(FMDSS.VahanINFO.parseCurrentDateToStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class parseCurrentDateToStringRequestBody {
        
        public parseCurrentDateToStringRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class parseCurrentDateToStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="parseCurrentDateToStringResponse", Namespace="http://server.web.vahan.nic/", Order=0)]
        public FMDSS.VahanINFO.parseCurrentDateToStringResponseBody Body;
        
        public parseCurrentDateToStringResponse() {
        }
        
        public parseCurrentDateToStringResponse(FMDSS.VahanINFO.parseCurrentDateToStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class parseCurrentDateToStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public parseCurrentDateToStringResponseBody() {
        }
        
        public parseCurrentDateToStringResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VahanInfoChannel : FMDSS.VahanINFO.VahanInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VahanInfoClient : System.ServiceModel.ClientBase<FMDSS.VahanINFO.VahanInfo>, FMDSS.VahanINFO.VahanInfo {
        
        public VahanInfoClient() {
        }
        
        public VahanInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VahanInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VahanInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VahanInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FMDSS.VahanINFO.getDetailsResponse FMDSS.VahanINFO.VahanInfo.getDetails(FMDSS.VahanINFO.getDetailsRequest request) {
            return base.Channel.getDetails(request);
        }
        
        public string getDetails(string client_id, string regn_no) {
            FMDSS.VahanINFO.getDetailsRequest inValue = new FMDSS.VahanINFO.getDetailsRequest();
            inValue.Body = new FMDSS.VahanINFO.getDetailsRequestBody();
            inValue.Body.client_id = client_id;
            inValue.Body.regn_no = regn_no;
            FMDSS.VahanINFO.getDetailsResponse retVal = ((FMDSS.VahanINFO.VahanInfo)(this)).getDetails(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FMDSS.VahanINFO.getDetailsResponse> FMDSS.VahanINFO.VahanInfo.getDetailsAsync(FMDSS.VahanINFO.getDetailsRequest request) {
            return base.Channel.getDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FMDSS.VahanINFO.getDetailsResponse> getDetailsAsync(string client_id, string regn_no) {
            FMDSS.VahanINFO.getDetailsRequest inValue = new FMDSS.VahanINFO.getDetailsRequest();
            inValue.Body = new FMDSS.VahanINFO.getDetailsRequestBody();
            inValue.Body.client_id = client_id;
            inValue.Body.regn_no = regn_no;
            return ((FMDSS.VahanINFO.VahanInfo)(this)).getDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FMDSS.VahanINFO.getChasisDetailsResponse FMDSS.VahanINFO.VahanInfo.getChasisDetails(FMDSS.VahanINFO.getChasisDetailsRequest request) {
            return base.Channel.getChasisDetails(request);
        }
        
        public string getChasisDetails(string client_id, string chasi_no) {
            FMDSS.VahanINFO.getChasisDetailsRequest inValue = new FMDSS.VahanINFO.getChasisDetailsRequest();
            inValue.Body = new FMDSS.VahanINFO.getChasisDetailsRequestBody();
            inValue.Body.client_id = client_id;
            inValue.Body.chasi_no = chasi_no;
            FMDSS.VahanINFO.getChasisDetailsResponse retVal = ((FMDSS.VahanINFO.VahanInfo)(this)).getChasisDetails(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FMDSS.VahanINFO.getChasisDetailsResponse> FMDSS.VahanINFO.VahanInfo.getChasisDetailsAsync(FMDSS.VahanINFO.getChasisDetailsRequest request) {
            return base.Channel.getChasisDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FMDSS.VahanINFO.getChasisDetailsResponse> getChasisDetailsAsync(string client_id, string chasi_no) {
            FMDSS.VahanINFO.getChasisDetailsRequest inValue = new FMDSS.VahanINFO.getChasisDetailsRequest();
            inValue.Body = new FMDSS.VahanINFO.getChasisDetailsRequestBody();
            inValue.Body.client_id = client_id;
            inValue.Body.chasi_no = chasi_no;
            return ((FMDSS.VahanINFO.VahanInfo)(this)).getChasisDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FMDSS.VahanINFO.getEngineDetailsResponse FMDSS.VahanINFO.VahanInfo.getEngineDetails(FMDSS.VahanINFO.getEngineDetailsRequest request) {
            return base.Channel.getEngineDetails(request);
        }
        
        public string getEngineDetails(string client_id, string engine_no) {
            FMDSS.VahanINFO.getEngineDetailsRequest inValue = new FMDSS.VahanINFO.getEngineDetailsRequest();
            inValue.Body = new FMDSS.VahanINFO.getEngineDetailsRequestBody();
            inValue.Body.client_id = client_id;
            inValue.Body.engine_no = engine_no;
            FMDSS.VahanINFO.getEngineDetailsResponse retVal = ((FMDSS.VahanINFO.VahanInfo)(this)).getEngineDetails(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FMDSS.VahanINFO.getEngineDetailsResponse> FMDSS.VahanINFO.VahanInfo.getEngineDetailsAsync(FMDSS.VahanINFO.getEngineDetailsRequest request) {
            return base.Channel.getEngineDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FMDSS.VahanINFO.getEngineDetailsResponse> getEngineDetailsAsync(string client_id, string engine_no) {
            FMDSS.VahanINFO.getEngineDetailsRequest inValue = new FMDSS.VahanINFO.getEngineDetailsRequest();
            inValue.Body = new FMDSS.VahanINFO.getEngineDetailsRequestBody();
            inValue.Body.client_id = client_id;
            inValue.Body.engine_no = engine_no;
            return ((FMDSS.VahanINFO.VahanInfo)(this)).getEngineDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FMDSS.VahanINFO.parseCurrentDateToStringResponse FMDSS.VahanINFO.VahanInfo.parseCurrentDateToString(FMDSS.VahanINFO.parseCurrentDateToStringRequest request) {
            return base.Channel.parseCurrentDateToString(request);
        }
        
        public string parseCurrentDateToString() {
            FMDSS.VahanINFO.parseCurrentDateToStringRequest inValue = new FMDSS.VahanINFO.parseCurrentDateToStringRequest();
            inValue.Body = new FMDSS.VahanINFO.parseCurrentDateToStringRequestBody();
            FMDSS.VahanINFO.parseCurrentDateToStringResponse retVal = ((FMDSS.VahanINFO.VahanInfo)(this)).parseCurrentDateToString(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FMDSS.VahanINFO.parseCurrentDateToStringResponse> FMDSS.VahanINFO.VahanInfo.parseCurrentDateToStringAsync(FMDSS.VahanINFO.parseCurrentDateToStringRequest request) {
            return base.Channel.parseCurrentDateToStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<FMDSS.VahanINFO.parseCurrentDateToStringResponse> parseCurrentDateToStringAsync() {
            FMDSS.VahanINFO.parseCurrentDateToStringRequest inValue = new FMDSS.VahanINFO.parseCurrentDateToStringRequest();
            inValue.Body = new FMDSS.VahanINFO.parseCurrentDateToStringRequestBody();
            return ((FMDSS.VahanINFO.VahanInfo)(this)).parseCurrentDateToStringAsync(inValue);
        }
    }
}
