//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMDSS.Forest_Ven_Workorder {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Forest_Ven_Workorder.forestSoap")]
    public interface forestSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVendors", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetVendors(string Username, string Password, string OfficeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVendors", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetVendorsAsync(string Username, string Password, string OfficeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWorkOrders", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetWorkOrders(string Username, string Password, string OfficeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWorkOrders", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetWorkOrdersAsync(string Username, string Password, string OfficeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface forestSoapChannel : FMDSS.Forest_Ven_Workorder.forestSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class forestSoapClient : System.ServiceModel.ClientBase<FMDSS.Forest_Ven_Workorder.forestSoap>, FMDSS.Forest_Ven_Workorder.forestSoap {
        
        public forestSoapClient() {
        }
        
        public forestSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public forestSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public forestSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public forestSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetVendors(string Username, string Password, string OfficeId) {
            return base.Channel.GetVendors(Username, Password, OfficeId);
        }
        
        public System.Threading.Tasks.Task<string> GetVendorsAsync(string Username, string Password, string OfficeId) {
            return base.Channel.GetVendorsAsync(Username, Password, OfficeId);
        }
        
        public string GetWorkOrders(string Username, string Password, string OfficeId) {
            return base.Channel.GetWorkOrders(Username, Password, OfficeId);
        }
        
        public System.Threading.Tasks.Task<string> GetWorkOrdersAsync(string Username, string Password, string OfficeId) {
            return base.Channel.GetWorkOrdersAsync(Username, Password, OfficeId);
        }
    }
}
