//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMDSS.RTI_APP_Services {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.rti.rajasthan.gov.in/WebService/", ConfigurationName="RTI_APP_Services.RTISoap")]
    public interface RTISoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetTransactionBySSOIDJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetTransactionBySSOIDJSON(string sso_id, string month, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetTransactionBySSOIDJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetTransactionBySSOIDJSONAsync(string sso_id, string month, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetTransactionBySSOIDXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FMDSS.RTI_APP_Services.CitizenTransaction[] GetTransactionBySSOIDXML(string sso_id, string month, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetTransactionBySSOIDXML", ReplyAction="*")]
        System.Threading.Tasks.Task<FMDSS.RTI_APP_Services.CitizenTransaction[]> GetTransactionBySSOIDXMLAsync(string sso_id, string month, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetTransactionBySSOIDDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetTransactionBySSOIDDataSet(string sso_id, string month, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetTransactionBySSOIDDataSet", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetTransactionBySSOIDDataSetAsync(string sso_id, string month, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetApplicationStatusJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetApplicationStatusJSON(string application_no, int iseng);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetApplicationStatusJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetApplicationStatusJSONAsync(string application_no, int iseng);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetApplicationStatusDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetApplicationStatusDataSet(string application_no, int iseng);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetApplicationStatusDataSet", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetApplicationStatusDataSetAsync(string application_no, int iseng);
        
        // CODEGEN: Generating message contract since message part namespace (https://rti.rajasthan.gov.in) does not match the default value (http://www.rti.rajasthan.gov.in/WebService/)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetApplicationStatusXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Application")]
        FMDSS.RTI_APP_Services.GetApplicationStatusXMLResponse GetApplicationStatusXML(FMDSS.RTI_APP_Services.GetApplicationStatusXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetApplicationStatusXML", ReplyAction="*")]
        System.Threading.Tasks.Task<FMDSS.RTI_APP_Services.GetApplicationStatusXMLResponse> GetApplicationStatusXMLAsync(FMDSS.RTI_APP_Services.GetApplicationStatusXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetAppealStatusJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAppealStatusJSON(string AppealNo, int iseng);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetAppealStatusJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetAppealStatusJSONAsync(string AppealNo, int iseng);
        
        // CODEGEN: Generating message contract since message part namespace (https://rti.rajasthan.gov.in) does not match the default value (http://www.rti.rajasthan.gov.in/WebService/)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetAppealStatusXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Appeal")]
        FMDSS.RTI_APP_Services.GetAppealStatusXMLResponse GetAppealStatusXML(FMDSS.RTI_APP_Services.GetAppealStatusXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetAppealStatusXML", ReplyAction="*")]
        System.Threading.Tasks.Task<FMDSS.RTI_APP_Services.GetAppealStatusXMLResponse> GetAppealStatusXMLAsync(FMDSS.RTI_APP_Services.GetAppealStatusXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetAppealStatusDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAppealStatusDataSet(string AppealNo, int iseng);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetAppealStatusDataSet", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAppealStatusDataSetAsync(string AppealNo, int iseng);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetDeptForDashBoardJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDeptForDashBoardJSON(string sso_id, string Role_Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetDeptForDashBoardJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetDeptForDashBoardJSONAsync(string sso_id, string Role_Name);
        
        // CODEGEN: Generating message contract since message part namespace (https://rti.rajasthan.gov.in) does not match the default value (http://www.rti.rajasthan.gov.in/WebService/)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetDeptForDashBoardXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DeptForDashBoard")]
        FMDSS.RTI_APP_Services.GetDeptForDashBoardXMLResponse GetDeptForDashBoardXML(FMDSS.RTI_APP_Services.GetDeptForDashBoardXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetDeptForDashBoardXML", ReplyAction="*")]
        System.Threading.Tasks.Task<FMDSS.RTI_APP_Services.GetDeptForDashBoardXMLResponse> GetDeptForDashBoardXMLAsync(FMDSS.RTI_APP_Services.GetDeptForDashBoardXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetDeptForDashBoardDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDeptForDashBoardDataSet(string sso_id, string Role_Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetDeptForDashBoardDataSet", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDeptForDashBoardDataSetAsync(string sso_id, string Role_Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetDeptForDashBoardstring", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDeptForDashBoardstring(string sso_id, string Role_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetDeptForDashBoardstring", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetDeptForDashBoardstringAsync(string sso_id, string Role_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetApplicationAllTransactionBySSOIDJSO" +
            "N", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetApplicationAllTransactionBySSOIDJSON(string SSO_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetApplicationAllTransactionBySSOIDJSO" +
            "N", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetApplicationAllTransactionBySSOIDJSONAsync(string SSO_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetAppealAllTransactionBySSOIDJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAppealAllTransactionBySSOIDJSON(string SSO_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetAppealAllTransactionBySSOIDJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetAppealAllTransactionBySSOIDJSONAsync(string SSO_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetSecondAppealsAllTransactionBySSOIDJ" +
            "SON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSecondAppealsAllTransactionBySSOIDJSON(string SSO_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetSecondAppealsAllTransactionBySSOIDJ" +
            "SON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetSecondAppealsAllTransactionBySSOIDJSONAsync(string SSO_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetComplaintsAllTransactionBySSOIDJSON" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetComplaintsAllTransactionBySSOIDJSON(string SSO_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetComplaintsAllTransactionBySSOIDJSON" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetComplaintsAllTransactionBySSOIDJSONAsync(string SSO_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetMAAllTransactionBySSOIDJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMAAllTransactionBySSOIDJSON(string SSO_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.rti.rajasthan.gov.in/WebService/GetMAAllTransactionBySSOIDJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetMAAllTransactionBySSOIDJSONAsync(string SSO_ID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://rti.rajasthan.gov.in")]
    public partial class CitizenTransaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sSOIDField;
        
        private string service_NameField;
        
        private string service_DetailField;
        
        private string request_IdField;
        
        private string transaction_StartTimeField;
        
        private string transaction_StatusField;
        
        private string transaction_StatusTimeField;
        
        private string transaction_IdField;
        
        private string paymentModeField;
        
        private string billAmountField;
        
        private string paidAmountField;
        
        private string channelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SSOID {
            get {
                return this.sSOIDField;
            }
            set {
                this.sSOIDField = value;
                this.RaisePropertyChanged("SSOID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Service_Name {
            get {
                return this.service_NameField;
            }
            set {
                this.service_NameField = value;
                this.RaisePropertyChanged("Service_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Service_Detail {
            get {
                return this.service_DetailField;
            }
            set {
                this.service_DetailField = value;
                this.RaisePropertyChanged("Service_Detail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Request_Id {
            get {
                return this.request_IdField;
            }
            set {
                this.request_IdField = value;
                this.RaisePropertyChanged("Request_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Transaction_StartTime {
            get {
                return this.transaction_StartTimeField;
            }
            set {
                this.transaction_StartTimeField = value;
                this.RaisePropertyChanged("Transaction_StartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Transaction_Status {
            get {
                return this.transaction_StatusField;
            }
            set {
                this.transaction_StatusField = value;
                this.RaisePropertyChanged("Transaction_Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Transaction_StatusTime {
            get {
                return this.transaction_StatusTimeField;
            }
            set {
                this.transaction_StatusTimeField = value;
                this.RaisePropertyChanged("Transaction_StatusTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Transaction_Id {
            get {
                return this.transaction_IdField;
            }
            set {
                this.transaction_IdField = value;
                this.RaisePropertyChanged("Transaction_Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PaymentMode {
            get {
                return this.paymentModeField;
            }
            set {
                this.paymentModeField = value;
                this.RaisePropertyChanged("PaymentMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string BillAmount {
            get {
                return this.billAmountField;
            }
            set {
                this.billAmountField = value;
                this.RaisePropertyChanged("BillAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PaidAmount {
            get {
                return this.paidAmountField;
            }
            set {
                this.paidAmountField = value;
                this.RaisePropertyChanged("PaidAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
                this.RaisePropertyChanged("Channel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://rti.rajasthan.gov.in")]
    public partial class DeptForDashBoard : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string department_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string department_id {
            get {
                return this.department_idField;
            }
            set {
                this.department_idField = value;
                this.RaisePropertyChanged("department_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://rti.rajasthan.gov.in")]
    public partial class Appeal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string citizenField;
        
        private string addressofcitizenField;
        
        private string outwardPerformedByField;
        
        private string outwardActivityField;
        
        private string outwardDateField;
        
        private string outwardNoField;
        
        private string outwardRemarksField;
        
        private string inwardNoField;
        
        private string inwardActivityField;
        
        private string inwardDateField;
        
        private string inwardPerformedByField;
        
        private string inwardRemarksField;
        
        private string inward_ActionTypeField;
        
        private string outward_ActionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Citizen {
            get {
                return this.citizenField;
            }
            set {
                this.citizenField = value;
                this.RaisePropertyChanged("Citizen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Addressofcitizen {
            get {
                return this.addressofcitizenField;
            }
            set {
                this.addressofcitizenField = value;
                this.RaisePropertyChanged("Addressofcitizen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OutwardPerformedBy {
            get {
                return this.outwardPerformedByField;
            }
            set {
                this.outwardPerformedByField = value;
                this.RaisePropertyChanged("OutwardPerformedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OutwardActivity {
            get {
                return this.outwardActivityField;
            }
            set {
                this.outwardActivityField = value;
                this.RaisePropertyChanged("OutwardActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OutwardDate {
            get {
                return this.outwardDateField;
            }
            set {
                this.outwardDateField = value;
                this.RaisePropertyChanged("OutwardDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string OutwardNo {
            get {
                return this.outwardNoField;
            }
            set {
                this.outwardNoField = value;
                this.RaisePropertyChanged("OutwardNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string OutwardRemarks {
            get {
                return this.outwardRemarksField;
            }
            set {
                this.outwardRemarksField = value;
                this.RaisePropertyChanged("OutwardRemarks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string InwardNo {
            get {
                return this.inwardNoField;
            }
            set {
                this.inwardNoField = value;
                this.RaisePropertyChanged("InwardNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string InwardActivity {
            get {
                return this.inwardActivityField;
            }
            set {
                this.inwardActivityField = value;
                this.RaisePropertyChanged("InwardActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string InwardDate {
            get {
                return this.inwardDateField;
            }
            set {
                this.inwardDateField = value;
                this.RaisePropertyChanged("InwardDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string InwardPerformedBy {
            get {
                return this.inwardPerformedByField;
            }
            set {
                this.inwardPerformedByField = value;
                this.RaisePropertyChanged("InwardPerformedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string InwardRemarks {
            get {
                return this.inwardRemarksField;
            }
            set {
                this.inwardRemarksField = value;
                this.RaisePropertyChanged("InwardRemarks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Inward_ActionType {
            get {
                return this.inward_ActionTypeField;
            }
            set {
                this.inward_ActionTypeField = value;
                this.RaisePropertyChanged("Inward_ActionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Outward_ActionType {
            get {
                return this.outward_ActionTypeField;
            }
            set {
                this.outward_ActionTypeField = value;
                this.RaisePropertyChanged("Outward_ActionType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://rti.rajasthan.gov.in")]
    public partial class Application : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string citizenField;
        
        private string addressofcitizenField;
        
        private string outwardPerformedByField;
        
        private string inwardDateField;
        
        private string outwardActivityField;
        
        private string inwardNoField;
        
        private string outwardNoField;
        
        private string inwardPerformedByField;
        
        private string inwardRemarksField;
        
        private string inward_ActionTypeField;
        
        private string outward_ActionTypeField;
        
        private string inwardActivityField;
        
        private string outwardDateField;
        
        private string outwardRemarksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Citizen {
            get {
                return this.citizenField;
            }
            set {
                this.citizenField = value;
                this.RaisePropertyChanged("Citizen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Addressofcitizen {
            get {
                return this.addressofcitizenField;
            }
            set {
                this.addressofcitizenField = value;
                this.RaisePropertyChanged("Addressofcitizen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OutwardPerformedBy {
            get {
                return this.outwardPerformedByField;
            }
            set {
                this.outwardPerformedByField = value;
                this.RaisePropertyChanged("OutwardPerformedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string InwardDate {
            get {
                return this.inwardDateField;
            }
            set {
                this.inwardDateField = value;
                this.RaisePropertyChanged("InwardDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OutwardActivity {
            get {
                return this.outwardActivityField;
            }
            set {
                this.outwardActivityField = value;
                this.RaisePropertyChanged("OutwardActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string InwardNo {
            get {
                return this.inwardNoField;
            }
            set {
                this.inwardNoField = value;
                this.RaisePropertyChanged("InwardNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string OutwardNo {
            get {
                return this.outwardNoField;
            }
            set {
                this.outwardNoField = value;
                this.RaisePropertyChanged("OutwardNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string InwardPerformedBy {
            get {
                return this.inwardPerformedByField;
            }
            set {
                this.inwardPerformedByField = value;
                this.RaisePropertyChanged("InwardPerformedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string InwardRemarks {
            get {
                return this.inwardRemarksField;
            }
            set {
                this.inwardRemarksField = value;
                this.RaisePropertyChanged("InwardRemarks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Inward_ActionType {
            get {
                return this.inward_ActionTypeField;
            }
            set {
                this.inward_ActionTypeField = value;
                this.RaisePropertyChanged("Inward_ActionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Outward_ActionType {
            get {
                return this.outward_ActionTypeField;
            }
            set {
                this.outward_ActionTypeField = value;
                this.RaisePropertyChanged("Outward_ActionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string InwardActivity {
            get {
                return this.inwardActivityField;
            }
            set {
                this.inwardActivityField = value;
                this.RaisePropertyChanged("InwardActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string OutwardDate {
            get {
                return this.outwardDateField;
            }
            set {
                this.outwardDateField = value;
                this.RaisePropertyChanged("OutwardDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string OutwardRemarks {
            get {
                return this.outwardRemarksField;
            }
            set {
                this.outwardRemarksField = value;
                this.RaisePropertyChanged("OutwardRemarks");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetApplicationStatusXML", WrapperNamespace="http://www.rti.rajasthan.gov.in/WebService/", IsWrapped=true)]
    public partial class GetApplicationStatusXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.rti.rajasthan.gov.in/WebService/", Order=0)]
        public string application_no;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.rti.rajasthan.gov.in/WebService/", Order=1)]
        public int iseng;
        
        public GetApplicationStatusXMLRequest() {
        }
        
        public GetApplicationStatusXMLRequest(string application_no, int iseng) {
            this.application_no = application_no;
            this.iseng = iseng;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetApplicationStatusXMLResponse", WrapperNamespace="http://www.rti.rajasthan.gov.in/WebService/", IsWrapped=true)]
    public partial class GetApplicationStatusXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://rti.rajasthan.gov.in", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="https://rti.rajasthan.gov.in")]
        public FMDSS.RTI_APP_Services.Application Application;
        
        public GetApplicationStatusXMLResponse() {
        }
        
        public GetApplicationStatusXMLResponse(FMDSS.RTI_APP_Services.Application Application) {
            this.Application = Application;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAppealStatusXML", WrapperNamespace="http://www.rti.rajasthan.gov.in/WebService/", IsWrapped=true)]
    public partial class GetAppealStatusXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.rti.rajasthan.gov.in/WebService/", Order=0)]
        public string AppealNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.rti.rajasthan.gov.in/WebService/", Order=1)]
        public int iseng;
        
        public GetAppealStatusXMLRequest() {
        }
        
        public GetAppealStatusXMLRequest(string AppealNo, int iseng) {
            this.AppealNo = AppealNo;
            this.iseng = iseng;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAppealStatusXMLResponse", WrapperNamespace="http://www.rti.rajasthan.gov.in/WebService/", IsWrapped=true)]
    public partial class GetAppealStatusXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://rti.rajasthan.gov.in", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="https://rti.rajasthan.gov.in")]
        public FMDSS.RTI_APP_Services.Appeal Appeal;
        
        public GetAppealStatusXMLResponse() {
        }
        
        public GetAppealStatusXMLResponse(FMDSS.RTI_APP_Services.Appeal Appeal) {
            this.Appeal = Appeal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeptForDashBoardXML", WrapperNamespace="http://www.rti.rajasthan.gov.in/WebService/", IsWrapped=true)]
    public partial class GetDeptForDashBoardXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.rti.rajasthan.gov.in/WebService/", Order=0)]
        public string sso_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.rti.rajasthan.gov.in/WebService/", Order=1)]
        public string Role_Name;
        
        public GetDeptForDashBoardXMLRequest() {
        }
        
        public GetDeptForDashBoardXMLRequest(string sso_id, string Role_Name) {
            this.sso_id = sso_id;
            this.Role_Name = Role_Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDeptForDashBoardXMLResponse", WrapperNamespace="http://www.rti.rajasthan.gov.in/WebService/", IsWrapped=true)]
    public partial class GetDeptForDashBoardXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://rti.rajasthan.gov.in", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="https://rti.rajasthan.gov.in")]
        public FMDSS.RTI_APP_Services.DeptForDashBoard DeptForDashBoard;
        
        public GetDeptForDashBoardXMLResponse() {
        }
        
        public GetDeptForDashBoardXMLResponse(FMDSS.RTI_APP_Services.DeptForDashBoard DeptForDashBoard) {
            this.DeptForDashBoard = DeptForDashBoard;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RTISoapChannel : FMDSS.RTI_APP_Services.RTISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RTISoapClient : System.ServiceModel.ClientBase<FMDSS.RTI_APP_Services.RTISoap>, FMDSS.RTI_APP_Services.RTISoap {
        
        public RTISoapClient() {
        }
        
        public RTISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RTISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RTISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RTISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTransactionBySSOIDJSON(string sso_id, string month, string year) {
            return base.Channel.GetTransactionBySSOIDJSON(sso_id, month, year);
        }
        
        public System.Threading.Tasks.Task<string> GetTransactionBySSOIDJSONAsync(string sso_id, string month, string year) {
            return base.Channel.GetTransactionBySSOIDJSONAsync(sso_id, month, year);
        }
        
        public FMDSS.RTI_APP_Services.CitizenTransaction[] GetTransactionBySSOIDXML(string sso_id, string month, string year) {
            return base.Channel.GetTransactionBySSOIDXML(sso_id, month, year);
        }
        
        public System.Threading.Tasks.Task<FMDSS.RTI_APP_Services.CitizenTransaction[]> GetTransactionBySSOIDXMLAsync(string sso_id, string month, string year) {
            return base.Channel.GetTransactionBySSOIDXMLAsync(sso_id, month, year);
        }
        
        public System.Data.DataSet GetTransactionBySSOIDDataSet(string sso_id, string month, string year) {
            return base.Channel.GetTransactionBySSOIDDataSet(sso_id, month, year);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetTransactionBySSOIDDataSetAsync(string sso_id, string month, string year) {
            return base.Channel.GetTransactionBySSOIDDataSetAsync(sso_id, month, year);
        }
        
        public string GetApplicationStatusJSON(string application_no, int iseng) {
            return base.Channel.GetApplicationStatusJSON(application_no, iseng);
        }
        
        public System.Threading.Tasks.Task<string> GetApplicationStatusJSONAsync(string application_no, int iseng) {
            return base.Channel.GetApplicationStatusJSONAsync(application_no, iseng);
        }
        
        public System.Data.DataTable GetApplicationStatusDataSet(string application_no, int iseng) {
            return base.Channel.GetApplicationStatusDataSet(application_no, iseng);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetApplicationStatusDataSetAsync(string application_no, int iseng) {
            return base.Channel.GetApplicationStatusDataSetAsync(application_no, iseng);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FMDSS.RTI_APP_Services.GetApplicationStatusXMLResponse FMDSS.RTI_APP_Services.RTISoap.GetApplicationStatusXML(FMDSS.RTI_APP_Services.GetApplicationStatusXMLRequest request) {
            return base.Channel.GetApplicationStatusXML(request);
        }
        
        public FMDSS.RTI_APP_Services.Application GetApplicationStatusXML(string application_no, int iseng) {
            FMDSS.RTI_APP_Services.GetApplicationStatusXMLRequest inValue = new FMDSS.RTI_APP_Services.GetApplicationStatusXMLRequest();
            inValue.application_no = application_no;
            inValue.iseng = iseng;
            FMDSS.RTI_APP_Services.GetApplicationStatusXMLResponse retVal = ((FMDSS.RTI_APP_Services.RTISoap)(this)).GetApplicationStatusXML(inValue);
            return retVal.Application;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FMDSS.RTI_APP_Services.GetApplicationStatusXMLResponse> FMDSS.RTI_APP_Services.RTISoap.GetApplicationStatusXMLAsync(FMDSS.RTI_APP_Services.GetApplicationStatusXMLRequest request) {
            return base.Channel.GetApplicationStatusXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<FMDSS.RTI_APP_Services.GetApplicationStatusXMLResponse> GetApplicationStatusXMLAsync(string application_no, int iseng) {
            FMDSS.RTI_APP_Services.GetApplicationStatusXMLRequest inValue = new FMDSS.RTI_APP_Services.GetApplicationStatusXMLRequest();
            inValue.application_no = application_no;
            inValue.iseng = iseng;
            return ((FMDSS.RTI_APP_Services.RTISoap)(this)).GetApplicationStatusXMLAsync(inValue);
        }
        
        public string GetAppealStatusJSON(string AppealNo, int iseng) {
            return base.Channel.GetAppealStatusJSON(AppealNo, iseng);
        }
        
        public System.Threading.Tasks.Task<string> GetAppealStatusJSONAsync(string AppealNo, int iseng) {
            return base.Channel.GetAppealStatusJSONAsync(AppealNo, iseng);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FMDSS.RTI_APP_Services.GetAppealStatusXMLResponse FMDSS.RTI_APP_Services.RTISoap.GetAppealStatusXML(FMDSS.RTI_APP_Services.GetAppealStatusXMLRequest request) {
            return base.Channel.GetAppealStatusXML(request);
        }
        
        public FMDSS.RTI_APP_Services.Appeal GetAppealStatusXML(string AppealNo, int iseng) {
            FMDSS.RTI_APP_Services.GetAppealStatusXMLRequest inValue = new FMDSS.RTI_APP_Services.GetAppealStatusXMLRequest();
            inValue.AppealNo = AppealNo;
            inValue.iseng = iseng;
            FMDSS.RTI_APP_Services.GetAppealStatusXMLResponse retVal = ((FMDSS.RTI_APP_Services.RTISoap)(this)).GetAppealStatusXML(inValue);
            return retVal.Appeal;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FMDSS.RTI_APP_Services.GetAppealStatusXMLResponse> FMDSS.RTI_APP_Services.RTISoap.GetAppealStatusXMLAsync(FMDSS.RTI_APP_Services.GetAppealStatusXMLRequest request) {
            return base.Channel.GetAppealStatusXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<FMDSS.RTI_APP_Services.GetAppealStatusXMLResponse> GetAppealStatusXMLAsync(string AppealNo, int iseng) {
            FMDSS.RTI_APP_Services.GetAppealStatusXMLRequest inValue = new FMDSS.RTI_APP_Services.GetAppealStatusXMLRequest();
            inValue.AppealNo = AppealNo;
            inValue.iseng = iseng;
            return ((FMDSS.RTI_APP_Services.RTISoap)(this)).GetAppealStatusXMLAsync(inValue);
        }
        
        public System.Data.DataSet GetAppealStatusDataSet(string AppealNo, int iseng) {
            return base.Channel.GetAppealStatusDataSet(AppealNo, iseng);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAppealStatusDataSetAsync(string AppealNo, int iseng) {
            return base.Channel.GetAppealStatusDataSetAsync(AppealNo, iseng);
        }
        
        public string GetDeptForDashBoardJSON(string sso_id, string Role_Name) {
            return base.Channel.GetDeptForDashBoardJSON(sso_id, Role_Name);
        }
        
        public System.Threading.Tasks.Task<string> GetDeptForDashBoardJSONAsync(string sso_id, string Role_Name) {
            return base.Channel.GetDeptForDashBoardJSONAsync(sso_id, Role_Name);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FMDSS.RTI_APP_Services.GetDeptForDashBoardXMLResponse FMDSS.RTI_APP_Services.RTISoap.GetDeptForDashBoardXML(FMDSS.RTI_APP_Services.GetDeptForDashBoardXMLRequest request) {
            return base.Channel.GetDeptForDashBoardXML(request);
        }
        
        public FMDSS.RTI_APP_Services.DeptForDashBoard GetDeptForDashBoardXML(string sso_id, string Role_Name) {
            FMDSS.RTI_APP_Services.GetDeptForDashBoardXMLRequest inValue = new FMDSS.RTI_APP_Services.GetDeptForDashBoardXMLRequest();
            inValue.sso_id = sso_id;
            inValue.Role_Name = Role_Name;
            FMDSS.RTI_APP_Services.GetDeptForDashBoardXMLResponse retVal = ((FMDSS.RTI_APP_Services.RTISoap)(this)).GetDeptForDashBoardXML(inValue);
            return retVal.DeptForDashBoard;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FMDSS.RTI_APP_Services.GetDeptForDashBoardXMLResponse> FMDSS.RTI_APP_Services.RTISoap.GetDeptForDashBoardXMLAsync(FMDSS.RTI_APP_Services.GetDeptForDashBoardXMLRequest request) {
            return base.Channel.GetDeptForDashBoardXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<FMDSS.RTI_APP_Services.GetDeptForDashBoardXMLResponse> GetDeptForDashBoardXMLAsync(string sso_id, string Role_Name) {
            FMDSS.RTI_APP_Services.GetDeptForDashBoardXMLRequest inValue = new FMDSS.RTI_APP_Services.GetDeptForDashBoardXMLRequest();
            inValue.sso_id = sso_id;
            inValue.Role_Name = Role_Name;
            return ((FMDSS.RTI_APP_Services.RTISoap)(this)).GetDeptForDashBoardXMLAsync(inValue);
        }
        
        public System.Data.DataSet GetDeptForDashBoardDataSet(string sso_id, string Role_Name) {
            return base.Channel.GetDeptForDashBoardDataSet(sso_id, Role_Name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDeptForDashBoardDataSetAsync(string sso_id, string Role_Name) {
            return base.Channel.GetDeptForDashBoardDataSetAsync(sso_id, Role_Name);
        }
        
        public string GetDeptForDashBoardstring(string sso_id, string Role_name) {
            return base.Channel.GetDeptForDashBoardstring(sso_id, Role_name);
        }
        
        public System.Threading.Tasks.Task<string> GetDeptForDashBoardstringAsync(string sso_id, string Role_name) {
            return base.Channel.GetDeptForDashBoardstringAsync(sso_id, Role_name);
        }
        
        public string GetApplicationAllTransactionBySSOIDJSON(string SSO_ID) {
            return base.Channel.GetApplicationAllTransactionBySSOIDJSON(SSO_ID);
        }
        
        public System.Threading.Tasks.Task<string> GetApplicationAllTransactionBySSOIDJSONAsync(string SSO_ID) {
            return base.Channel.GetApplicationAllTransactionBySSOIDJSONAsync(SSO_ID);
        }
        
        public string GetAppealAllTransactionBySSOIDJSON(string SSO_ID) {
            return base.Channel.GetAppealAllTransactionBySSOIDJSON(SSO_ID);
        }
        
        public System.Threading.Tasks.Task<string> GetAppealAllTransactionBySSOIDJSONAsync(string SSO_ID) {
            return base.Channel.GetAppealAllTransactionBySSOIDJSONAsync(SSO_ID);
        }
        
        public string GetSecondAppealsAllTransactionBySSOIDJSON(string SSO_ID) {
            return base.Channel.GetSecondAppealsAllTransactionBySSOIDJSON(SSO_ID);
        }
        
        public System.Threading.Tasks.Task<string> GetSecondAppealsAllTransactionBySSOIDJSONAsync(string SSO_ID) {
            return base.Channel.GetSecondAppealsAllTransactionBySSOIDJSONAsync(SSO_ID);
        }
        
        public string GetComplaintsAllTransactionBySSOIDJSON(string SSO_ID) {
            return base.Channel.GetComplaintsAllTransactionBySSOIDJSON(SSO_ID);
        }
        
        public System.Threading.Tasks.Task<string> GetComplaintsAllTransactionBySSOIDJSONAsync(string SSO_ID) {
            return base.Channel.GetComplaintsAllTransactionBySSOIDJSONAsync(SSO_ID);
        }
        
        public string GetMAAllTransactionBySSOIDJSON(string SSO_ID) {
            return base.Channel.GetMAAllTransactionBySSOIDJSON(SSO_ID);
        }
        
        public System.Threading.Tasks.Task<string> GetMAAllTransactionBySSOIDJSONAsync(string SSO_ID) {
            return base.Channel.GetMAAllTransactionBySSOIDJSONAsync(SSO_ID);
        }
    }
}
