//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMDSS.BhamashaServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.esb.org/PRDWSDL/", ConfigurationName="BhamashaServices.PRDWSDL")]
    public interface PRDWSDL {
        
        // CODEGEN: Generating message contract since element name scheme from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esb.org/PRDWSDL/accrual", ReplyAction="*")]
        FMDSS.BhamashaServices.accrualResponse accrual(FMDSS.BhamashaServices.accrualRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esb.org/PRDWSDL/accrual", ReplyAction="*")]
        System.Threading.Tasks.Task<FMDSS.BhamashaServices.accrualResponse> accrualAsync(FMDSS.BhamashaServices.accrualRequest request);
        
        // CODEGEN: Generating message contract since element name reqXml from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esb.org/PRDWSDL/bankmapping", ReplyAction="*")]
        FMDSS.BhamashaServices.bankmappingResponse bankmapping(FMDSS.BhamashaServices.bankmappingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esb.org/PRDWSDL/bankmapping", ReplyAction="*")]
        System.Threading.Tasks.Task<FMDSS.BhamashaServices.bankmappingResponse> bankmappingAsync(FMDSS.BhamashaServices.bankmappingRequest request);
        
        // CODEGEN: Generating message contract since element name reqXml from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esb.org/PRDWSDL/bhamashahInfo", ReplyAction="*")]
        FMDSS.BhamashaServices.bhamashahInfoResponse bhamashahInfo(FMDSS.BhamashaServices.bhamashahInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esb.org/PRDWSDL/bhamashahInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<FMDSS.BhamashaServices.bhamashahInfoResponse> bhamashahInfoAsync(FMDSS.BhamashaServices.bhamashahInfoRequest request);
        
        // CODEGEN: Generating message contract since element name reqXml from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esb.org/PRDWSDL/mapping", ReplyAction="*")]
        FMDSS.BhamashaServices.mappingResponse mapping(FMDSS.BhamashaServices.mappingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esb.org/PRDWSDL/mapping", ReplyAction="*")]
        System.Threading.Tasks.Task<FMDSS.BhamashaServices.mappingResponse> mappingAsync(FMDSS.BhamashaServices.mappingRequest request);
        
        // CODEGEN: Generating message contract since element name scheme from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esb.org/PRDWSDL/transaction", ReplyAction="*")]
        FMDSS.BhamashaServices.transactionResponse transaction(FMDSS.BhamashaServices.transactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esb.org/PRDWSDL/transaction", ReplyAction="*")]
        System.Threading.Tasks.Task<FMDSS.BhamashaServices.transactionResponse> transactionAsync(FMDSS.BhamashaServices.transactionRequest request);
        
        // CODEGEN: Generating message contract since element name scheme from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esb.org/PRDWSDL/withdrawl", ReplyAction="*")]
        FMDSS.BhamashaServices.withdrawlResponse withdrawl(FMDSS.BhamashaServices.withdrawlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esb.org/PRDWSDL/withdrawl", ReplyAction="*")]
        System.Threading.Tasks.Task<FMDSS.BhamashaServices.withdrawlResponse> withdrawlAsync(FMDSS.BhamashaServices.withdrawlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class accrualRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="accrual", Namespace="http://www.esb.org/PRDWSDL/", Order=0)]
        public FMDSS.BhamashaServices.accrualRequestBody Body;
        
        public accrualRequest() {
        }
        
        public accrualRequest(FMDSS.BhamashaServices.accrualRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class accrualRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string scheme;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string reqXml;
        
        public accrualRequestBody() {
        }
        
        public accrualRequestBody(string scheme, string reqXml) {
            this.scheme = scheme;
            this.reqXml = reqXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class accrualResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="accrualResponse", Namespace="http://www.esb.org/PRDWSDL/", Order=0)]
        public FMDSS.BhamashaServices.accrualResponseBody Body;
        
        public accrualResponse() {
        }
        
        public accrualResponse(FMDSS.BhamashaServices.accrualResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class accrualResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public accrualResponseBody() {
        }
        
        public accrualResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bankmappingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bankmapping", Namespace="http://www.esb.org/PRDWSDL/", Order=0)]
        public FMDSS.BhamashaServices.bankmappingRequestBody Body;
        
        public bankmappingRequest() {
        }
        
        public bankmappingRequest(FMDSS.BhamashaServices.bankmappingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bankmappingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reqXml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string scheme;
        
        public bankmappingRequestBody() {
        }
        
        public bankmappingRequestBody(string reqXml, string scheme) {
            this.reqXml = reqXml;
            this.scheme = scheme;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bankmappingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bankmappingResponse", Namespace="http://www.esb.org/PRDWSDL/", Order=0)]
        public FMDSS.BhamashaServices.bankmappingResponseBody Body;
        
        public bankmappingResponse() {
        }
        
        public bankmappingResponse(FMDSS.BhamashaServices.bankmappingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bankmappingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bankmappingResponseBody() {
        }
        
        public bankmappingResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bhamashahInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bhamashahInfo", Namespace="http://www.esb.org/PRDWSDL/", Order=0)]
        public FMDSS.BhamashaServices.bhamashahInfoRequestBody Body;
        
        public bhamashahInfoRequest() {
        }
        
        public bhamashahInfoRequest(FMDSS.BhamashaServices.bhamashahInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bhamashahInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reqXml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string scheme;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string infoFlg;
        
        public bhamashahInfoRequestBody() {
        }
        
        public bhamashahInfoRequestBody(string reqXml, string scheme, string infoFlg) {
            this.reqXml = reqXml;
            this.scheme = scheme;
            this.infoFlg = infoFlg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bhamashahInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bhamashahInfoResponse", Namespace="http://www.esb.org/PRDWSDL/", Order=0)]
        public FMDSS.BhamashaServices.bhamashahInfoResponseBody Body;
        
        public bhamashahInfoResponse() {
        }
        
        public bhamashahInfoResponse(FMDSS.BhamashaServices.bhamashahInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bhamashahInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bhamashahInfoResponseBody() {
        }
        
        public bhamashahInfoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mappingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mapping", Namespace="http://www.esb.org/PRDWSDL/", Order=0)]
        public FMDSS.BhamashaServices.mappingRequestBody Body;
        
        public mappingRequest() {
        }
        
        public mappingRequest(FMDSS.BhamashaServices.mappingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class mappingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reqXml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string scheme;
        
        public mappingRequestBody() {
        }
        
        public mappingRequestBody(string reqXml, string scheme) {
            this.reqXml = reqXml;
            this.scheme = scheme;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mappingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mappingResponse", Namespace="http://www.esb.org/PRDWSDL/", Order=0)]
        public FMDSS.BhamashaServices.mappingResponseBody Body;
        
        public mappingResponse() {
        }
        
        public mappingResponse(FMDSS.BhamashaServices.mappingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class mappingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public mappingResponseBody() {
        }
        
        public mappingResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class transactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="transaction", Namespace="http://www.esb.org/PRDWSDL/", Order=0)]
        public FMDSS.BhamashaServices.transactionRequestBody Body;
        
        public transactionRequest() {
        }
        
        public transactionRequest(FMDSS.BhamashaServices.transactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class transactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string scheme;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string reqXml;
        
        public transactionRequestBody() {
        }
        
        public transactionRequestBody(string scheme, string reqXml) {
            this.scheme = scheme;
            this.reqXml = reqXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class transactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="transactionResponse", Namespace="http://www.esb.org/PRDWSDL/", Order=0)]
        public FMDSS.BhamashaServices.transactionResponseBody Body;
        
        public transactionResponse() {
        }
        
        public transactionResponse(FMDSS.BhamashaServices.transactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class transactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public transactionResponseBody() {
        }
        
        public transactionResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class withdrawlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="withdrawl", Namespace="http://www.esb.org/PRDWSDL/", Order=0)]
        public FMDSS.BhamashaServices.withdrawlRequestBody Body;
        
        public withdrawlRequest() {
        }
        
        public withdrawlRequest(FMDSS.BhamashaServices.withdrawlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class withdrawlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string scheme;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string reqXml;
        
        public withdrawlRequestBody() {
        }
        
        public withdrawlRequestBody(string scheme, string reqXml) {
            this.scheme = scheme;
            this.reqXml = reqXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class withdrawlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="withdrawlResponse", Namespace="http://www.esb.org/PRDWSDL/", Order=0)]
        public FMDSS.BhamashaServices.withdrawlResponseBody Body;
        
        public withdrawlResponse() {
        }
        
        public withdrawlResponse(FMDSS.BhamashaServices.withdrawlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class withdrawlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public withdrawlResponseBody() {
        }
        
        public withdrawlResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PRDWSDLChannel : FMDSS.BhamashaServices.PRDWSDL, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PRDWSDLClient : System.ServiceModel.ClientBase<FMDSS.BhamashaServices.PRDWSDL>, FMDSS.BhamashaServices.PRDWSDL {
        
        public PRDWSDLClient() {
        }
        
        public PRDWSDLClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PRDWSDLClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PRDWSDLClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PRDWSDLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FMDSS.BhamashaServices.accrualResponse FMDSS.BhamashaServices.PRDWSDL.accrual(FMDSS.BhamashaServices.accrualRequest request) {
            return base.Channel.accrual(request);
        }
        
        public string accrual(string scheme, string reqXml) {
            FMDSS.BhamashaServices.accrualRequest inValue = new FMDSS.BhamashaServices.accrualRequest();
            inValue.Body = new FMDSS.BhamashaServices.accrualRequestBody();
            inValue.Body.scheme = scheme;
            inValue.Body.reqXml = reqXml;
            FMDSS.BhamashaServices.accrualResponse retVal = ((FMDSS.BhamashaServices.PRDWSDL)(this)).accrual(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FMDSS.BhamashaServices.accrualResponse> FMDSS.BhamashaServices.PRDWSDL.accrualAsync(FMDSS.BhamashaServices.accrualRequest request) {
            return base.Channel.accrualAsync(request);
        }
        
        public System.Threading.Tasks.Task<FMDSS.BhamashaServices.accrualResponse> accrualAsync(string scheme, string reqXml) {
            FMDSS.BhamashaServices.accrualRequest inValue = new FMDSS.BhamashaServices.accrualRequest();
            inValue.Body = new FMDSS.BhamashaServices.accrualRequestBody();
            inValue.Body.scheme = scheme;
            inValue.Body.reqXml = reqXml;
            return ((FMDSS.BhamashaServices.PRDWSDL)(this)).accrualAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FMDSS.BhamashaServices.bankmappingResponse FMDSS.BhamashaServices.PRDWSDL.bankmapping(FMDSS.BhamashaServices.bankmappingRequest request) {
            return base.Channel.bankmapping(request);
        }
        
        public string bankmapping(string reqXml, string scheme) {
            FMDSS.BhamashaServices.bankmappingRequest inValue = new FMDSS.BhamashaServices.bankmappingRequest();
            inValue.Body = new FMDSS.BhamashaServices.bankmappingRequestBody();
            inValue.Body.reqXml = reqXml;
            inValue.Body.scheme = scheme;
            FMDSS.BhamashaServices.bankmappingResponse retVal = ((FMDSS.BhamashaServices.PRDWSDL)(this)).bankmapping(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FMDSS.BhamashaServices.bankmappingResponse> FMDSS.BhamashaServices.PRDWSDL.bankmappingAsync(FMDSS.BhamashaServices.bankmappingRequest request) {
            return base.Channel.bankmappingAsync(request);
        }
        
        public System.Threading.Tasks.Task<FMDSS.BhamashaServices.bankmappingResponse> bankmappingAsync(string reqXml, string scheme) {
            FMDSS.BhamashaServices.bankmappingRequest inValue = new FMDSS.BhamashaServices.bankmappingRequest();
            inValue.Body = new FMDSS.BhamashaServices.bankmappingRequestBody();
            inValue.Body.reqXml = reqXml;
            inValue.Body.scheme = scheme;
            return ((FMDSS.BhamashaServices.PRDWSDL)(this)).bankmappingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FMDSS.BhamashaServices.bhamashahInfoResponse FMDSS.BhamashaServices.PRDWSDL.bhamashahInfo(FMDSS.BhamashaServices.bhamashahInfoRequest request) {
            return base.Channel.bhamashahInfo(request);
        }
        
        public string bhamashahInfo(string reqXml, string scheme, string infoFlg) {
            FMDSS.BhamashaServices.bhamashahInfoRequest inValue = new FMDSS.BhamashaServices.bhamashahInfoRequest();
            inValue.Body = new FMDSS.BhamashaServices.bhamashahInfoRequestBody();
            inValue.Body.reqXml = reqXml;
            inValue.Body.scheme = scheme;
            inValue.Body.infoFlg = infoFlg;
            FMDSS.BhamashaServices.bhamashahInfoResponse retVal = ((FMDSS.BhamashaServices.PRDWSDL)(this)).bhamashahInfo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FMDSS.BhamashaServices.bhamashahInfoResponse> FMDSS.BhamashaServices.PRDWSDL.bhamashahInfoAsync(FMDSS.BhamashaServices.bhamashahInfoRequest request) {
            return base.Channel.bhamashahInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FMDSS.BhamashaServices.bhamashahInfoResponse> bhamashahInfoAsync(string reqXml, string scheme, string infoFlg) {
            FMDSS.BhamashaServices.bhamashahInfoRequest inValue = new FMDSS.BhamashaServices.bhamashahInfoRequest();
            inValue.Body = new FMDSS.BhamashaServices.bhamashahInfoRequestBody();
            inValue.Body.reqXml = reqXml;
            inValue.Body.scheme = scheme;
            inValue.Body.infoFlg = infoFlg;
            return ((FMDSS.BhamashaServices.PRDWSDL)(this)).bhamashahInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FMDSS.BhamashaServices.mappingResponse FMDSS.BhamashaServices.PRDWSDL.mapping(FMDSS.BhamashaServices.mappingRequest request) {
            return base.Channel.mapping(request);
        }
        
        public string mapping(string reqXml, string scheme) {
            FMDSS.BhamashaServices.mappingRequest inValue = new FMDSS.BhamashaServices.mappingRequest();
            inValue.Body = new FMDSS.BhamashaServices.mappingRequestBody();
            inValue.Body.reqXml = reqXml;
            inValue.Body.scheme = scheme;
            FMDSS.BhamashaServices.mappingResponse retVal = ((FMDSS.BhamashaServices.PRDWSDL)(this)).mapping(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FMDSS.BhamashaServices.mappingResponse> FMDSS.BhamashaServices.PRDWSDL.mappingAsync(FMDSS.BhamashaServices.mappingRequest request) {
            return base.Channel.mappingAsync(request);
        }
        
        public System.Threading.Tasks.Task<FMDSS.BhamashaServices.mappingResponse> mappingAsync(string reqXml, string scheme) {
            FMDSS.BhamashaServices.mappingRequest inValue = new FMDSS.BhamashaServices.mappingRequest();
            inValue.Body = new FMDSS.BhamashaServices.mappingRequestBody();
            inValue.Body.reqXml = reqXml;
            inValue.Body.scheme = scheme;
            return ((FMDSS.BhamashaServices.PRDWSDL)(this)).mappingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FMDSS.BhamashaServices.transactionResponse FMDSS.BhamashaServices.PRDWSDL.transaction(FMDSS.BhamashaServices.transactionRequest request) {
            return base.Channel.transaction(request);
        }
        
        public string transaction(string scheme, string reqXml) {
            FMDSS.BhamashaServices.transactionRequest inValue = new FMDSS.BhamashaServices.transactionRequest();
            inValue.Body = new FMDSS.BhamashaServices.transactionRequestBody();
            inValue.Body.scheme = scheme;
            inValue.Body.reqXml = reqXml;
            FMDSS.BhamashaServices.transactionResponse retVal = ((FMDSS.BhamashaServices.PRDWSDL)(this)).transaction(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FMDSS.BhamashaServices.transactionResponse> FMDSS.BhamashaServices.PRDWSDL.transactionAsync(FMDSS.BhamashaServices.transactionRequest request) {
            return base.Channel.transactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FMDSS.BhamashaServices.transactionResponse> transactionAsync(string scheme, string reqXml) {
            FMDSS.BhamashaServices.transactionRequest inValue = new FMDSS.BhamashaServices.transactionRequest();
            inValue.Body = new FMDSS.BhamashaServices.transactionRequestBody();
            inValue.Body.scheme = scheme;
            inValue.Body.reqXml = reqXml;
            return ((FMDSS.BhamashaServices.PRDWSDL)(this)).transactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FMDSS.BhamashaServices.withdrawlResponse FMDSS.BhamashaServices.PRDWSDL.withdrawl(FMDSS.BhamashaServices.withdrawlRequest request) {
            return base.Channel.withdrawl(request);
        }
        
        public string withdrawl(string scheme, string reqXml) {
            FMDSS.BhamashaServices.withdrawlRequest inValue = new FMDSS.BhamashaServices.withdrawlRequest();
            inValue.Body = new FMDSS.BhamashaServices.withdrawlRequestBody();
            inValue.Body.scheme = scheme;
            inValue.Body.reqXml = reqXml;
            FMDSS.BhamashaServices.withdrawlResponse retVal = ((FMDSS.BhamashaServices.PRDWSDL)(this)).withdrawl(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FMDSS.BhamashaServices.withdrawlResponse> FMDSS.BhamashaServices.PRDWSDL.withdrawlAsync(FMDSS.BhamashaServices.withdrawlRequest request) {
            return base.Channel.withdrawlAsync(request);
        }
        
        public System.Threading.Tasks.Task<FMDSS.BhamashaServices.withdrawlResponse> withdrawlAsync(string scheme, string reqXml) {
            FMDSS.BhamashaServices.withdrawlRequest inValue = new FMDSS.BhamashaServices.withdrawlRequest();
            inValue.Body = new FMDSS.BhamashaServices.withdrawlRequestBody();
            inValue.Body.scheme = scheme;
            inValue.Body.reqXml = reqXml;
            return ((FMDSS.BhamashaServices.PRDWSDL)(this)).withdrawlAsync(inValue);
        }
    }
}
